afb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

import afb.views
import mainmenu.views

urlpatterns = [
    url(r'^afb-adm/', admin.site.urls, name='admin'),
    path('', mainmenu.views.home, name='home'),
    path('home/', mainmenu.views.home, name='home'),
    path('help/', mainmenu.views.help, name='help'),
    path('login/', afb.views.LoginView.as_view(), name='login'),
    path('logout/', afb.views.LogoutView.as_view(), name='logout'),
    path('report/', include(('report.urls', 'report'), namespace='report')),
    path('alatberat/', include(('alatberat.urls', 'alatberat'), namespace='alatberat')),
    path('bbm/', include(('bbm.urls', 'bbm'), namespace='bbm')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

alatberat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add_biaya_ab/$', views.BiayaabAddView.as_view(), name='add_biaya_ab'),
    url(r'^add_hour_meter/$', views.HourmeterAddView.as_view(), name='add_hour_meter')
]

bbm/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add_transaksi_tangki_induk/$', views.TransaksitangkiindukAddView.as_view(), name='add_transaksi_tangki_induk'),
    url(r'^add_transaksi_mobil_tangki/$', views.TransaksimobiltangkiAddView.as_view(), name='add_transaksi_mobil_tangki'),
]

report/urls.py
from django.conf.urls import url

from . import views
from .views import export as export_views
from .views import summary_report

urlpatterns = [
    url(r'^$', views.ReportIndexView.as_view(), name='index'),
    url(r'^hour_meter$', views.HourmeterReportView.as_view(), name='hour_meter'),
    url(r'^biaya_per_alat$', views.BiayaabPerAlatReportView.as_view(), name='biaya_per_alat'),
    url(r'^biaya_per_tanggal$', views. BiayaabPerTanggalReportView.as_view(), name='biaya_per_tanggal'),
    url(r'^bbm_alat_berat$', views.BBMabReportView.as_view(), name='bbm_ab'),
    url(r'^transaksi_tangki_induk$', views.TransaksiTangkiIndukReportView.as_view(), name='transaksi_tangki_induk'),
    url(r'^transaksi_mobil_tangki$', views.TransaksiMobilTangkiReportView.as_view(), name='transaksi_mobil_tangki'),
    url(r'^hasil_produksi$', views.ProduksiReportView.as_view(), name='hasil_produksi'),
    url(r'^export_hour_meter$', export_views.HourMeterExportView.as_view(), name='export_hour_meter'),
    url(r'^export_biaya_per_alat$', export_views.BiayaabPerAlatExportView.as_view(), name='export_biaya_per_alat'),
    url(r'^export_biaya_per_tanggal$', export_views.BiayaabPerTanggalExportView.as_view(), name='export_biaya_per_tanggal'),
    url(r'^export_bbm_ab$', export_views.BBMabExportView.as_view(), name='export_bbm_ab'),
    url(r'^export_transaksi_tangki_induk', export_views.TransaksiTangkiIndukExportView.as_view(), name='export_transaksi_tangki_induk'),
    url(r'^export_transaksi_mobil_tangki', export_views.TransaksiMobilTangkiExportView.as_view(), name='export_transaksi_mobil_tangki'),
    url(r'^export_produksi', export_views.ProduksiExportView.as_view(), name='export_produksi'),

    # Summary reports view
    url(r'^summary_report_operator', summary_report.ReportOperatorView.as_view(),
        name='summary_report_operator'),
    url(r'^summary_report_gaji', summary_report.ReportGajiView.as_view(),
        name='summary_report_gaji'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">
    <link rel="stylesheet" href="{% static 'datepicker/dist/css/DatePickerX.min.css' %}">
    <script src="{% static 'datepicker/dist/js/DatePickerX.min.js' %}"></script>
    {% block extra_head %}{% endblock %}

    <title>{% block title %}AFB Application{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom mb-4">
		<div class="container">
			<div class="flex-grow-1 navbar-date">{% now "l j F Y" %}</div>
			<a class="navbar-brand font-weight-bold mx-auto" href="{% url 'home' %}">PT. AFB</a>
			
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-expand" aria-controls="navbar-expand" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbar-expand">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link text-dark" href="{% url 'home' %}">Home</a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link text-dark" href="{% url 'help' %}">Help</a>
					</li>
					
					{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link text-dark" href="{% url 'logout' %}">Logout</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link text-dark" href="{% url 'login' %}">Login</a>
						</li>
					{% endif %}
					
					<li class="nav-item">
						<a class="nav-link text-dark" href="{% url 'report:index' %}">Report</a>
					</li>
					
					{% if user.is_staff %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
						</li>
					{% endif %}
				</ul>
			</div> <!-- /.collapse menu -->
		</div>
	</nav> <!-- /.navbar -->

    <div class="container">
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
					<div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'success' %}success{% endif %} alert-dismissible">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						{{message}}
					</div>
				{% endfor %}
			</ul>
      {% endif %}
    </div>

    {% block content %}

    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md">
					<img class="mb-2" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
					<small class="d-block mb-3 text-muted"><h5>© 2019</h5></small>
				</div>
				
				<div class="col-6 col-md">
					<h5>Features</h5>
					<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="http://www.google.com" target="_blank">Google</a></li>
					<li><a class="text-muted" href="http://www.usrparts.com/" target="_blank">Komatsu Parts</a></li>
					<li><a class="text-muted" href="#">Team feature</a></li>
					</ul>
				</div>
			</div>
        </div> <!-- /.container -->
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>


</body>
</html>

templates/help.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/Article-List.css">
    <link rel="stylesheet" href="/Highlight-Blue.css">
    <link rel="stylesheet" href="/styles.css">
</head>

<body>
    <div id="about" class="highlight-blue">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Jika Anda Membutuhkan Bantuan</h2>
                <p class="text-center">Anda mengalami kesulitan dan membutuhkan bantuan ? Hubungi kami dengan cara ini</p>
            </div>
        </div>
    </div>
    <div class="article-list">
        <div class="container">
            <div class="intro">
                <p class="text-center"></p>
            </div>
            <div class="row articles">
                <div class="col-sm-6 col-md-4 item" style="width: 100;height: 100;"><a href="http://www.anydesk.com" target="_blank"><img class="img-fluid" src="{% static 'AnyDesk-Logo-large.png' %}"  style="width: 300px;"></a>
                    <h3 class="name">Download Anydesk</h3>
                    <p class="description">Download Anydesk di www.anydesk.com dan jalankan.<br>Informasikan kepada kami id anydesk anda</p><a class="action" href="#"><i class="fa fa-arrow-circle-right"></i></a></div>
                <div class="col-sm-6 col-md-4 item"><a href="http://www.whatsapp.com" target="_blank"><img class="img-fluid" src="{% static 'whatsapp_PNG15.png' %}" style="width: 100px;"></a>
                    <h3 class="name">Whatsapp</h3>
                    <p class="description">Hubungi kami via whatsapp :<br>081933915990</p><a class="action" href="http://www.whatsapp.com" target="_blank"><i class="fa fa-arrow-circle-right"></i></a></div>
                <div class="col-sm-6 col-md-4 item"></div>
            </div>
        </div>
    </div>
    <script src="/js/jquery-3.3.1.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script id="bs-live-reload" data-sseport="46083" data-lastchange="1558355083960" src="/js/livereload.js"></script>
</body>

</html>

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Selamat Datang</h1>
</div>
<div class="container">
  <div class="mb-3 text-center row">
	<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
		<div class="card mb-4 box-shadow h-100">
			<div class="card-header" style="background-color: rgb(255, 110, 110);">
				<h4 class="my-0 font-weight-normal"><b>Tangki Induk</b></h4>
			</div>
			
			<div class="card-body"><img src="{% static 'pistol.png' %}" height="128" width="128" style="">
				<ul class="list-unstyled mt-3 mb-4">
					<li>Input Pemakaian<br>Tangki Induk</li>
				</ul>
				
				<p><a class="btn btn-lg btn-block btn-primary" href="{% url 'bbm:add_transaksi_tangki_induk' %}" role="button" style="background-color: rgb(255, 110, 110)">Click</a></p>
			</div>
		</div>
	</div>
	
	<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
		<div class="card mb-4 box-shadow h-100">
			<div class="card-header" style="background-color: rgb(255, 110, 110);">
				<h4 class="my-0 font-weight-normal"><b>Mobil Tangki</b></h4>
			</div>
			
			<div class="card-body"><img src="{% static 'pistol.png' %}" height="128" width="128" style="">
				<ul class="list-unstyled mt-3 mb-4">
					<li>Input Pemakaian<br>Mobil Tangki</li>
				</ul>
				
				<p><a class="btn btn-lg btn-block btn-primary" href="{% url 'bbm:add_transaksi_mobil_tangki' %}" role="button" style="background-color: rgb(255, 110, 110)">Click</a></p>
			</div>
		</div>
	</div>
	
	<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
		<div class="card mb-4 box-shadow h-100">
			<div class="card-header" style="background-color: rgb(255, 110, 110);">
				<h4 class="my-0 font-weight-normal"><b>Service</b></h4>
			</div>
			
			<div class="card-body"><img src="{% static 'service.png' %}" height="128" width="128" style="">
				<ul class="list-unstyled mt-3 mb-4">
					<li>Input Biaya Service <br>Alat Berat</li>
				</ul>
				
				<p><a class="btn btn-lg btn-block btn-primary" href="{% url 'alatberat:add_biaya_ab' %}" role="button" style="background-color: rgb(255, 110, 110)">Click</a></p>
			</div>
		</div>
	</div>
	
	<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
		<div class="card mb-4 box-shadow h-100">
			<div class="card-header" style="background-color: rgb(255, 110, 110);">
				<h4 class="my-0 font-weight-normal"><b>Hour Meter</b></h4>
			</div>
			
			<div class="card-body"><img src="{% static 'hourmeter.png' %}" height="128" width="128" style="">
				<ul class="list-unstyled mt-3 mb-4">
					<li>Input<br>Hour Meter</li>
				</ul>
				
				<p><a class="btn btn-lg btn-block btn-primary" href="{% url 'alatberat:add_hour_meter' %}" role="button" style="background-color: rgb(255, 110, 110)">Click</a></p>
			</div>
		</div>
	</div>
	
    {% if user.is_staff %}
		<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
			<div class="card mb-4 box-shadow h-100">
				<div class="card-header" style="background-color: rgb(255, 110, 110);">
					<h4 class="my-0 font-weight-normal"><b>Admin Area</b></h4>
				</div>
				
				<div class="card-body"><img src="{% static 'admin.jpg'%}" height="128" width="128" style="">
					<ul class="list-unstyled mt-3 mb-4">
						<li>Input<br>Admin</li>
					</ul>
					
					<p><a class="btn btn-lg btn-block btn-primary" href="{% url 'admin:index' %}" role="button" style="background-color: rgb(255, 110, 110)">Click</a></p>
				</div>
			</div>
		</div>
    {% endif %}

  </div>

</div>

{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
{% endblock %}

{% block content %}
  <div class="login-clean">
    <form method="post">
        {% csrf_token %}
        <h2 class="sr-only">Login Form</h2>
        <div class="illustration">
            <h4>Welcome to <br>AFB System </h4><i class="icon ion-android-people"></i></div>
        <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Nama Pengguna" required=""></div>
        <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password" required=""></div>
        <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Log In</button></div><a class="forgot" href="#">Forgot your email or password?</a>
    </form>
  </div>
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}