afb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

import afb.views
import mainmenu.views

urlpatterns = [
    url(r'^afb-adm/', admin.site.urls, name='admin'),
    path('', mainmenu.views.home, name='home'),
    path('home/', mainmenu.views.home, name='home'),
    path('help/', mainmenu.views.help, name='help'),
    path('login/', afb.views.LoginView.as_view(), name='login'),
    path('logout/', afb.views.LogoutView.as_view(), name='logout'),
    path('report/', include(('report.urls', 'report'), namespace='report')),
    path('alatberat/', include(('alatberat.urls', 'alatberat'), namespace='alatberat')),
    path('bbm/', include(('bbm.urls', 'bbm'), namespace='bbm')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.conf.urls import url

from . import views
from .views import export as export_views
from .views import summary_report

urlpatterns = [
    url(r'^$', views.ReportIndexView.as_view(), name='index'),
    url(r'^hour_meter$', views.HourmeterReportView.as_view(), name='hour_meter'),
    url(r'^biaya_per_alat$', views.BiayaabPerAlatReportView.as_view(), name='biaya_per_alat'),
    url(r'^biaya_per_tanggal$', views. BiayaabPerTanggalReportView.as_view(), name='biaya_per_tanggal'),
    url(r'^bbm_alat_berat$', views.BBMabReportView.as_view(), name='bbm_ab'),
    url(r'^transaksi_tangki_induk$', views.TransaksiTangkiIndukReportView.as_view(), name='transaksi_tangki_induk'),
    url(r'^transaksi_mobil_tangki$', views.TransaksiMobilTangkiReportView.as_view(), name='transaksi_mobil_tangki'),
    url(r'^hasil_produksi$', views.ProduksiReportView.as_view(), name='hasil_produksi'),
    url(r'^export_hour_meter$', export_views.HourMeterExportView.as_view(), name='export_hour_meter'),
    url(r'^export_biaya_per_alat$', export_views.BiayaabPerAlatExportView.as_view(), name='export_biaya_per_alat'),
    url(r'^export_biaya_per_tanggal$', export_views.BiayaabPerTanggalExportView.as_view(), name='export_biaya_per_tanggal'),
    url(r'^export_bbm_ab$', export_views.BBMabExportView.as_view(), name='export_bbm_ab'),
    url(r'^export_transaksi_tangki_induk', export_views.TransaksiTangkiIndukExportView.as_view(), name='export_transaksi_tangki_induk'),
    url(r'^export_transaksi_mobil_tangki', export_views.TransaksiMobilTangkiExportView.as_view(), name='export_transaksi_mobil_tangki'),
    url(r'^export_produksi', export_views.ProduksiExportView.as_view(), name='export_produksi'),

    # Summary reports view
    url(r'^summary_report_operator', summary_report.ReportOperatorView.as_view(),
        name='summary_report_operator'),
    url(r'^summary_report_gaji', summary_report.ReportGajiView.as_view(),
        name='summary_report_gaji'),
]

report/models.py
from django.db import models

# Create your models here.

report/forms.py
from django import forms

from alatberat.models import Hourmeter, Alatberat, Operatorab, Biayaab, Bbmab
from bbm.models import Mobiltangki, Tangkiinduk, Transaksitangkiinduk, Transaksimobiltangki
from .utils import reverse_date_format

"""
ALAT BERAT FORM
"""


# Mixin for date range form
class DateRangeFormMixin(forms.Form):
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['start_date'].widget.attrs = {'class': 'form-control mr-3', "placeholder": "Start Date"}
        self.fields['end_date'].widget.attrs = {'class': 'form-control mr-3', "placeholder": "End Date"}

    def clean_start_date(self):
        start_date = self.data['start_date']
        end_date = self.data['end_date']
        if start_date > end_date:
            raise forms.ValidationError('Mohon periksa kembali tanggal pencarian anda')
        return reverse_date_format(start_date)

    def clean_end_date(self):
        end_date = self.data['end_date']
        return reverse_date_format(end_date)


class HourmeterReportForm(DateRangeFormMixin, forms.ModelForm):
    class Meta:
        model = Hourmeter
        fields = ('alatid', 'operatorid')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['alatid'].widget.attrs = {'class': 'form-control mr-3'}
        self.fields['operatorid'].widget.attrs = {'class': 'form-control mr-3'}
        self.fields['alatid'].queryset = Alatberat.objects.all()
        self.fields['operatorid'].queryset = Operatorab.objects.all()


class BiayaPerAlatReportForm(DateRangeFormMixin, forms.ModelForm):
    class Meta:
        model = Biayaab
        fields = ('alatid', 'start_date', 'end_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['alatid'].widget.attrs = {'class': 'form-control mr-3'}
        self.fields['alatid'].queryset = Alatberat.objects.all()


class BiayaPerTanggalReportForm(DateRangeFormMixin):
    pass


# Inherit Biaya per alat form due to the similarity
class BBMReportForm(BiayaPerAlatReportForm):
    class Meta:
        model = Bbmab
        fields = ('alatid', 'start_date', 'end_date')


class TransaksiTangkiIndukForm(DateRangeFormMixin, forms.ModelForm):
    class Meta:
        model = Transaksitangkiinduk
        fields = ('tangkiid', 'start_date', 'end_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tangkiid'].widget.attrs = {'class': 'form-control mr-3'}
        self.fields['tangkiid'].queryset = Tangkiinduk.objects.all()


class TransaksiMobilTangkiForm(DateRangeFormMixin, forms.ModelForm):
    class Meta:
        model = Transaksimobiltangki
        fields = ('mobilid', 'start_date', 'end_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mobilid'].widget.attrs = {'class': 'form-control mr-3'}
        self.fields['mobilid'].queryset = Mobiltangki.objects.all()


class ProduksiReportForm(DateRangeFormMixin):
    pass

report/views/export.py
import csv
from io import BytesIO

from datetime import datetime
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

from alatberat.models import Alatberat
from bbm.models import Tangkiinduk, Mobiltangki
from report.utils import reverse_date_format
from report.views import HourmeterReportView, BiayaabPerAlatReportView, BiayaabPerTanggalReportView, BBMabReportView
from report.views import TransaksiTangkiIndukReportView, TransaksiMobilTangkiReportView
from report.views import ProduksiReportView


def get_current_datetime_string():
    now = datetime.now()
    now_string = now.strftime('%Y-%m-%d__%H:%M:%S')
    return now_string


class ExportRendererView(object):
    object_exportables = []

    def get_title(self):
        title = self.title_prefix
        try:
            start_date = reverse_date_format(self.request.GET['start_date'])
            end_date = reverse_date_format(self.request.GET['end_date'])
            title = "{} {} sampai {}".format(title, start_date, end_date)
        except Exception:
            pass
        return title

    def get_filename(self):
        return self.export_filename

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["inner_template_name"] = self.inner_template_name
        return context

    def render_pdf_response(self, context):
        template = get_template('report/pdf_template.html')
        html = template.render(context)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            http_response = HttpResponse(response.getvalue(), content_type='application/pdf')
            return http_response
        else:
            return HttpResponse("Error Rendering PDF", status=400)

    def render_csv_response(self, context):
        response = HttpResponse(content_type='text/csv')
        exportables = ["nomor"] + self.object_exportables
        writer = csv.DictWriter(response, fieldnames=exportables)
        writer.writeheader()
        for counter, obj in enumerate(self.object_list, 1):
            data = {}
            data["nomor"] = counter
            try:
                for key in self.object_exportables:
                    data[key] = getattr(obj, key)
                writer.writerow(data)
            except KeyError as error_message:
                error_message = "No such key '{}'".format(error_message)
                messages.add_message(self.request, messages.ERROR, error_message)
                return HttpResponseRedirect(self.request.META['HTTP_REFERER'])
        return response

    def render_to_response(self, context, **response_kwargs):
        if not self.object_list:
            return HttpResponseRedirect(self.request.META['HTTP_REFERER'])

        context['title'] = self.get_title()
        if 'export_csv' not in self.request.GET:
            response = self.render_pdf_response(context)
            file_type = 'pdf'
        else:
            response = self.render_csv_response(context)
            file_type = 'csv'
        response['Content-Disposition'] = 'attachment; filename={}.{}'.format(self.get_filename(), file_type)
        return response


class ObjectDetailExportView(ExportRendererView):
    def get_obj_detail(self):
        objectid = int(self.request.GET[self.object_key])
        obj = self.object_model.objects.get(pk=objectid)
        return obj

    def get_filename(self):
        filename = super().get_filename()
        filename = "{}__{}".format(filename, self.get_obj_detail())
        return filename

    def get_title(self):
        title = super().get_title()
        title = "{} ({})".format(title, self.get_obj_detail())
        return title


class HourMeterExportView(ObjectDetailExportView, HourmeterReportView):
    inner_template_name = "report/report_hour_meter_inner.html"
    export_filename = "{}_Hour_Meter".format(get_current_datetime_string())
    title_prefix = "Hour Meter Report"
    object_key = 'alatid'
    object_model = Alatberat
    object_exportables = [
        'tanggal', 'operator_name', 'hmawal',
        'hmakhir', 'jam', 'hmdunia',
        'ot', 'shift', 'keterangan'
    ]


class BiayaabPerAlatExportView(ObjectDetailExportView, BiayaabPerAlatReportView):
    inner_template_name = "report/report_biaya_ab_alat_inner.html"
    export_filename = "{}_Biaya_AB_per_Alat".format(get_current_datetime_string())
    title_prefix = "Biaya Alat Berat"
    object_key = 'alatid'
    object_model = Alatberat
    object_exportables = ['tanggal', 'keterangan', 'biaya']


class BiayaabPerTanggalExportView(ExportRendererView, BiayaabPerTanggalReportView):
    inner_template_name = "report/report_biaya_ab_tanggal_inner.html"
    export_filename = "{}_Biaya_AB_Per_Tanggal".format(get_current_datetime_string())
    title_prefix = "Biaya Alat Berat Per Tanggal"
    object_exportables = ['tanggal', 'alatid', 'keterangan', 'biaya']


class BBMabExportView(ObjectDetailExportView, BBMabReportView):
    inner_template_name = "report/report_bbm_ab_inner.html"
    export_filename = "{}_BBM_Alat_berat".format(get_current_datetime_string())
    title_prefix = "BBM Alat Berat"
    object_key = 'alatid'
    object_model = Alatberat
    object_exportables = ['tanggal', 'hmnow', 'hmbefore', 'ltrmasuk', 'keterangan']


class TransaksiTangkiIndukExportView(ObjectDetailExportView, TransaksiTangkiIndukReportView):
    inner_template_name = "report/report_transaksi_tangki_induk_inner.html"
    export_filename = "{}_Transaksi_Tangki_Induk".format(get_current_datetime_string())
    title_prefix = "Transaksi Tangki Induk"
    object_key = 'tangkiid'
    object_model = Tangkiinduk
    object_exportables = ['tanggal', 'keterangan', 'agentid', 'mobilid', 'masuk', 'keluar', 'amount', 'sisa']


class TransaksiMobilTangkiExportView(ObjectDetailExportView, TransaksiMobilTangkiReportView):
    inner_template_name = "report/report_transaksi_mobil_tangki_inner.html"
    export_filename = "{}_Transaksi_Mobil_Tangki".format(get_current_datetime_string())
    title_prefix = "Transaksi Mobil Tangki"
    object_key = 'mobilid'
    object_model = Mobiltangki
    object_exportables = ['tanggal', 'alatid', 'kendaraanid', 'keluar', 'keterangan']


class ProduksiExportView(ExportRendererView, ProduksiReportView):
    inner_template_name = "report/report_produksi_inner.html"
    export_filename = "{}_Hasil_Produksi".format(get_current_datetime_string())
    title_prefix = "Hasil Produksi"
    object_exportables = ['tanggal', 'hasil', 'keterangan']

templates/report/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Lihat Report</h1>
  </div>

	<div class="container">
		<div class="mb-3 text-center row">
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Hour Meter</b></h4>
					</div>
					
					<div class="card-body">
						<a href="{% url 'report:hour_meter' %}">
							<i class="fa fa-clock-o fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Hour Meter</li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Servis Alat Berat</b></h4>
					</div>
					
					<div class="card-body">
					<a href="{% url 'report:biaya_per_alat' %}">
							<i class="fa fa-dashboard fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Biaya Servis per Alat Berat</li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Servis per Tanggal</b></h4>
					</div>
					
					<div class="card-body">
						<a href="{% url 'report:biaya_per_tanggal' %}">
							<i class="fa fa-calendar fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Biaya Servis Alat Berat per Tanggal</li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>BBM Alat Berat</b></h4>
					</div>
					
					<div class="card-body">
						<a href="{% url 'report:bbm_ab' %}">
							<i class="fa fa-tint fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report BBM Alat Berat</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="mb-3 text-center row">
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Tangki Induk</b></h4>
					</div>
					
					<div class="card-body">
					<a href="{% url 'report:transaksi_tangki_induk' %}">
							<i class="fa fa-bus fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Transaksi Tangki Induk</li>
						</ul>
					</div>
				</div>
			</div>
		
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Transaksi Mobil Tangki</b></h4>
					</div>
					
					<div class="card-body">
						<a href="{% url 'report:transaksi_mobil_tangki' %}">
							<i class="fa fa-truck fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Biaya Transaksi Mobil Tangki</li>
						</ul>
					</div>
				</div>
			</div>
		
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 mb-4">
				<div class="card box-shadow h-100">
					<div class="card-header" style="background-color: rgb(255, 110, 110);">
						<h4 class="my-0 font-weight-normal"><b>Hasil Produksi</b></h4>
					</div>
					
					<div class="card-body">
						<a href="{% url 'report:hasil_produksi' %}">
							<i class="fa fa-industry fa-3x"></i>
						</a>

						<ul class="list-unstyled mt-3 mb-4">
							<li>Lihat Report Hasil Produksi</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/report/pdf_template.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <style type="text/css">
      @page {
        size: A4;
        margin: 1cm;
      }
      h1{
        text-align: center;
      }
      .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
      }
      .table th,
      .table td {
        padding: 5px;
        vertical-align: top;
        border: 1px solid #000;
        /*text-align: center;*/
      }
      .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
      }
      .table tbody + tbody {
        border-top: 2px solid #000;
      }
      .table .table {
        background-color: #fff;
      }
      .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
      }
      .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
      }
      .text-right{
        text-align: right;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>{{title}}</h1>
      {% include inner_template_name %}
    </div>
  </body>
</html>

templates/report/report_bbm_ab.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Lihat Report BBM Alat Berat</h1>
  </div>
  <div class="container">
    <div class="card-deck mb-3 text-center">
      <form class="form-inline" method="POST" role="search" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label class="label mr-2" for="alatberatid">Alat Berat</label>
          {{form.alatid}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="start_date">Start Date</label>
          {{form.start_date}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="end_date">End Date</label>
          {{form.end_date}}
        </div>

        <button type="submit" class="btn btn-primary">Cari</button>
      </form>
    </div>
    <div class="card-deck mb-3 text-center">
      <h3>Search result</h3>
      {% include "report/report_bbm_ab_inner.html" %}
    </div>
    {% if object_list %}
      <div class="text-right">
        <a href="{% url 'report:export_bbm_ab' %}?{{request.GET.urlencode}}" class="mr-2">Export as PDF</a>
        <a href="{% url 'report:export_bbm_ab' %}?{{request.GET.urlencode}}&export_csv=1" class="mr-2">Export as CSV</a>
      </div>
    {% endif %}
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', function(){
      var start_date = document.querySelector('input[name="start_date"]')
      var end_date = document.querySelector('input[name="end_date"]')

      start_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

      end_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

    });
  </script>

{% endblock %}

templates/report/report_bbm_ab_inner.html
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nomor</th>
      <th>Tanggal</th>
      <th>Hm Now</th>
      <th>Hm Before</th>
      <th>Jumlah Liter</th>
      <th>Keterangan</th>
    </tr>
  </thead>
  <tbody>
    {% if object_list %}
      {% for obj in object_list%}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{obj.tanggal}}</td>
          <td>{{obj.hmnow}}</td>
          <td>{{obj.hmbefore}}</td>
          <td>{{obj.ltrmasuk}}</td>
          <td>{% if obj.keterangan %}{{obj.keterangan}}{% else %}-{% endif %}</td>
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="6">No Data</td>
      </tr>
    {% endif %}
  </tbody>
  <tfoot>
    <tr>
      <td class="text-right" colspan="5">Total</td>
      <td>{{total_bbm}}</td>
    </tr>
  </tfoot>
</table>

templates/report/report_biaya_ab_tanggal.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Lihat Report Biaya per Tanggal</h1>
  </div>
  <div class="container">
    <div class="card-deck mb-3 text-center">
      <form class="form-inline" method="POST" role="search" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label class="label mr-2" for="start_date">Start Date</label>
          {{form.start_date}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="end_date">End Date</label>
          {{form.end_date}}
        </div>

        <button type="submit" class="btn btn-primary">Cari</button>
      </form>
    </div>
    <div class="card-deck mb-3 text-center">
      <h3>Search result</h3>
      {% include "report/report_biaya_ab_tanggal_inner.html" %}
    </div>
    {% if object_list %}
      <div class="text-right">
        <a href="{% url 'report:export_biaya_per_tanggal' %}?{{request.GET.urlencode}}" class="mr-2">Export as PDF</a>
        <a href="{% url 'report:export_biaya_per_tanggal' %}?{{request.GET.urlencode}}&export_csv=1" class="mr-2">Export as CSV</a>
      </div>
    {% endif %}
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', function(){
      var start_date = document.querySelector('input[name="start_date"]')
      var end_date = document.querySelector('input[name="end_date"]')

      start_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

      end_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

    });
  </script>

{% endblock %}

templates/report/report_hour_meter.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Lihat Report Hour Meter</h1>
  </div>
  <div class="container">
    <div class="card-deck mb-3 text-center">
      <form class="form-inline" method="POST" role="search" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label class="label mr-2" for="alatberatid">Alat Berat</label>
          {{form.alatid}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="operatorid">Operator</label>
          {{form.operatorid}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="start_date">Start Date</label>
          {{form.start_date}}
        </div>

        <div class="form-group">
          <label class="label mr-2" for="end_date">End Date</label>
          {{form.end_date}}
        </div>

        <button type="submit" class="btn btn-primary">Cari</button>
      </form>
    </div>
    <div class="card-deck mb-3 text-center">
      <h3>Search result</h3>
      {% include "report/report_hour_meter_inner.html"%}
    </div>
    {% if object_list %}
      <div class="text-right">
        <a href="{% url 'report:export_hour_meter' %}?{{request.GET.urlencode}}" class="mr-2">Export as PDF</a>
        <a href="{% url 'report:export_hour_meter' %}?{{request.GET.urlencode}}&export_csv=1" class="mr-2">Export as CSV</a>
      </div>
    {% endif %}

    {% if is_paginated and object_list %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                {% if page_obj.number == 1 %}
                    <li class="disabled"><span>⇤</span></li>
                {% else %}
                    <li>
                        <a class="page-link" href="?alatid={{ alat_id }}&amp;operatorid={{ operator_id }}&amp;start_date={{ start_date }}&amp;end_date={{ end_date }}&amp;page=1">⇤</a>
                    </li>
                {% endif %}
            
                <li>
                    <a class="page-link" href="?alatid={{ alat_id }}&amp;operatorid={{ operator_id }}&amp;start_date={{ start_date }}&amp;end_date={{ end_date }}&amp;page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
            {% endif %}
            
            {% for i in proper_paginate %}
                {% if page_obj.number == i %}
                    <li class="page-link active bg-primary text-white">
                        <span>{{ i }} <span class="sr-only">(current)</span></span>
                    </li>
                {% else %}
                    <li>
                        <a class="page-link" href="?alatid={{ alat_id }}&amp;operatorid={{ operator_id }}&amp;start_date={{ start_date }}&amp;end_date={{ end_date }}&amp;page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li>
                    <a class="page-link" href="?alatid={{ alat_id }}&amp;operatorid={{ operator_id }}&amp;start_date={{ start_date }}&amp;end_date={{ end_date }}&amp;page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
            
                {% if page_obj.number == paginator.num_pages %}
                    <li class="disabled"><span>⇥</span></li>
                {% else %}
                    <li>
                        <a class="page-link" href="?alatid={{ alat_id }}&amp;operatorid={{ operator_id }}&amp;start_date={{ start_date }}&amp;end_date={{ end_date }}&amp;page={{ paginator.num_pages }}">⇥</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    {% endif %}
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', function(){
      var start_date = document.querySelector('input[name="start_date"]')
      var end_date = document.querySelector('input[name="end_date"]')

      start_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

      end_date.DatePickerX.init({
        format: "dd-mm-yyyy"
      });

    });
  </script>

{% endblock %}